(define (calculate-change amount)
    (define (cc amount denominations)
        (cond ((= amount 0) 1)
            ((or (= denominations 0) (< amount 0)) 0)
            (else (+ (cc amount (- denominations 1))
                    (cc (- amount (first-denomination denominations)) denominations)))))

    (define (first-denomination type)
        (cond ((= type 1) 1)
            ((= type 2) 5)
            ((= type 3) 10)
            ((= type 4) 25)
            ((= type 5) 50)))
    (cc amount 5))
